### ISSUE TITLE
 plain beginner explanations  better with code example what is prototype  for rec sys

### ISSUE THREAD

**Issue by Sandy4321** [karapostK/ProtoMF#2]
may you share some link for plain beginner explanations 
better with code example what is prototype  for rec sys

 a prototype is defined as an
entity (e. g., in the form of an embedding) that is representative of
a set of similar instances and is part of the observed data points, or
an artifact that summarizes a subset of instances with similar characteristics

https://karapostk.github.io/assets/pdf/melchiorre2022protomf.pdf

**Comment by karapostK** [comment]
Hey!
I have now pushed the utilities functions that I used to interpret the prototypes and generate the explanations for the recommendations. I added comments in order to simplify their usage, however I haven't tested them in a while even though they were working before.
https://github.com/karapostK/ProtoMF/blob/main/utilities/explanations_utils.py

Follow the instructions in the functions and you should be able to re-create the tables and pictures in the table (given a trained model). Hope this helps!
